spring.application.name=Auth-Service

server.port=8100

# Connecting to postgres DB for storing User details (use env here)
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/AuthServiceDB
spring.r2dbc.username=postgres
spring.r2dbc.password=1234

# Force Spring to run schema.sql at startup
spring.sql.init.mode=always
# Optional: Continue even if a table already exists (prevents crash on 2nd run)
spring.sql.init.continue-on-error=true

# JWT secret keys (Remove them from here and use env)
JWT_SECRET="ksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfioh"
# Expires after (set to 1 day for now 1000 * 60 * 60 * 24)
JWT_EXPIRATION=86400000