spring.application.name=Service-A

# User env for this
server.port=${SERVER_PORT:8081}

eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://discovery-service:8761/eureka