# Use Env for all these
server.port=8080

# JWT secret keys (Remove them from here and use env)
JWT_SECRET="ksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfioh"
# Expires after (set to 1 day for now 1000 * 60 * 60 * 24)
JWT_EXPIRATION=86400000

# Redis connection (use env)
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=1234
spring.data.redis.username=default

# Logging config
logback.log.file.path=./logs/test
# Show only warnings and errors from the framework
logging.level.org.springframework.cloud.gateway=WARN
# Keep your custom logic at INFO or DEBUG so you can see your Upstream/Downstream logs
logging.level.com.server.gateway=INFO

# Monitoring config
# Expose health and metrics endpoints
management.endpoints.web.exposure.include=health,metrics,prometheus,info
# Show full health details (disk space, db status, etc.)
management.endpoint.health.show-details=always