# Use Env for all these
server.port=8080

# JWT secret keys (Remove them from here and use env)
JWT_SECRET="ksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfiohiholdaiholdghjbkvhoawuqpieopwnmcadjaklvbnmbakjelhquiyllidhajkbcjkahgdhauhauiiohlioawhdvfjhkoksfjhfsklelkfjseajwlfioh"
# Expires after (set to 1 day for now 1000 * 60 * 60 * 24)
JWT_EXPIRATION=86400000